-- ============================================================================
-- Mr Center — تحكم وصول الطالب وتسوية عجز العهدة بصورة محاسبية سليمة
-- التاريخ: 2026-09-13
-- يفضّل تشغيله بعد 20260913_accounting_operations.sql. ينشئ متطلبات الجلسة
-- الآمنة بنفسه إن لم يُشغّل 20260912_security.sql في هذه القاعدة بعد.
-- ============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- متطلبات الجلسة الآمنة: هذا الترحيل يعمل أيضاً في قاعدة قائمة لم يُشغّل فيها
-- 20260912_security.sql بعد. لا يغيّر جدولاً موجوداً، بل ينشئ الحد الأدنى
-- المتوافق معه حتى لا تتعطل أجهزة الطلاب أو الجلسة الواحدة.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_active_sessions (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  session_key TEXT NOT NULL,
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.user_active_sessions ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.claim_session(p_key TEXT)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'not_authenticated'; END IF;
  IF p_key IS NULL OR length(trim(p_key)) < 8 OR length(trim(p_key)) > 128 THEN RAISE EXCEPTION 'invalid_session_key'; END IF;
  INSERT INTO public.user_active_sessions(user_id, session_key, started_at, last_seen)
  VALUES(auth.uid(), trim(p_key), now(), now())
  ON CONFLICT (user_id) DO UPDATE SET session_key = EXCLUDED.session_key, started_at = now(), last_seen = now();
END;
$$;
GRANT EXECUTE ON FUNCTION public.claim_session(TEXT) TO authenticated;

CREATE OR REPLACE FUNCTION public.check_session(p_key TEXT)
RETURNS BOOLEAN LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF auth.uid() IS NULL THEN RETURN false; END IF;
  IF NOT EXISTS (SELECT 1 FROM public.user_active_sessions WHERE user_id = auth.uid() AND session_key = p_key) THEN RETURN false; END IF;
  UPDATE public.user_active_sessions SET last_seen = now() WHERE user_id = auth.uid() AND session_key = p_key;
  RETURN true;
END;
$$;
GRANT EXECUTE ON FUNCTION public.check_session(TEXT) TO authenticated;

CREATE TABLE IF NOT EXISTS public.login_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  device_id TEXT NOT NULL DEFAULT '',
  success BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_login_attempts_email_time ON public.login_attempts(email, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_login_attempts_device_time ON public.login_attempts(device_id, created_at DESC);
ALTER TABLE public.login_attempts ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.record_login_attempt(p_email TEXT, p_device TEXT, p_success BOOLEAN)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.login_attempts(email, device_id, success, created_at)
  VALUES(lower(trim(p_email)), COALESCE(p_device, ''), COALESCE(p_success, false), now());
END;
$$;
GRANT EXECUTE ON FUNCTION public.record_login_attempt(TEXT, TEXT, BOOLEAN) TO anon, authenticated;

-- ----------------------------------------------------------------------------
-- ١) أجهزة الطلاب: السجل مفصول تماماً عن site_visitors العام.
-- الحجب هنا مقيد بالطالب والسنتر، فلا يمكن أن يعاقب جهازاً يستخدمه طالب
-- في سنتر آخر، ولا يملك المالك أي صلاحية على أجهزة سنتر آخر.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.student_device_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  center_id UUID NOT NULL REFERENCES public.centers(id) ON DELETE CASCADE,
  student_id TEXT NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  device_id TEXT NOT NULL,
  blocked BOOLEAN NOT NULL DEFAULT false,
  note TEXT NOT NULL DEFAULT '',
  first_seen TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen TIMESTAMPTZ NOT NULL DEFAULT now(),
  blocked_at TIMESTAMPTZ,
  UNIQUE(center_id, student_id, device_id)
);
CREATE INDEX IF NOT EXISTS idx_student_device_sessions_student
  ON public.student_device_sessions(center_id, student_id, last_seen DESC);
ALTER TABLE public.student_device_sessions ENABLE ROW LEVEL SECURITY;
-- لا توجد سياسة مباشرة: الوصول يكون فقط عبر RPCs محددة أدناه.

-- يحتفظ مفتاح الجلسة الحالي بمعرف الجهاز حتى يمكن إنهاء الجهاز المقصود فقط.
ALTER TABLE public.user_active_sessions
  ADD COLUMN IF NOT EXISTS device_id TEXT;

-- يسجل الطالب جهازه الحالي بعد الدخول؛ الأدوار الأخرى لا تنشئ صفوفاً هنا.
CREATE OR REPLACE FUNCTION public.register_current_student_device(p_device TEXT)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_center UUID; v_student TEXT;
BEGIN
  IF auth.uid() IS NULL OR p_device IS NULL OR length(trim(p_device)) < 8 OR length(trim(p_device)) > 128 THEN RETURN; END IF;
  SELECT center_id, student_id INTO v_center, v_student
  FROM public.profiles WHERE id = auth.uid() AND role = 'student';
  IF v_center IS NULL OR v_student IS NULL THEN RETURN; END IF;
  IF NOT EXISTS (SELECT 1 FROM public.students WHERE id = v_student AND center_id = v_center) THEN RETURN; END IF;

  INSERT INTO public.student_device_sessions(center_id, student_id, device_id, last_seen)
  VALUES(v_center, v_student, trim(p_device), now())
  ON CONFLICT(center_id, student_id, device_id) DO UPDATE SET last_seen = now();
  UPDATE public.user_active_sessions SET device_id = trim(p_device)
  WHERE user_id = auth.uid();
END;
$$;
GRANT EXECUTE ON FUNCTION public.register_current_student_device(TEXT) TO authenticated;

-- يفحصه العميل دورياً مع الجلسة. لا يوجد سجل للجهاز = متاح (توافق مع الأجهزة القديمة).
CREATE OR REPLACE FUNCTION public.check_current_student_device(p_device TEXT)
RETURNS BOOLEAN LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
DECLARE v_center UUID; v_student TEXT; v_role TEXT;
BEGIN
  IF auth.uid() IS NULL THEN RETURN false; END IF;
  SELECT role, center_id, student_id INTO v_role, v_center, v_student FROM public.profiles WHERE id = auth.uid();
  IF v_role IS DISTINCT FROM 'student' THEN RETURN true; END IF;
  IF v_center IS NULL OR v_student IS NULL OR p_device IS NULL OR trim(p_device) = '' THEN RETURN true; END IF;
  RETURN NOT EXISTS (
    SELECT 1 FROM public.student_device_sessions
    WHERE center_id = v_center AND student_id = v_student AND device_id = trim(p_device) AND blocked
  );
END;
$$;
GRANT EXECUTE ON FUNCTION public.check_current_student_device(TEXT) TO authenticated;

-- لا تعرض الأجهزة إلا لصاحب السنتر الذي يملك الطالب ذاته.
CREATE OR REPLACE FUNCTION public.list_student_devices(p_student TEXT)
RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
DECLARE v_center UUID := public.my_center_id();
BEGIN
  IF v_center IS NULL OR NOT public.admin_owns_center(v_center)
     OR NOT EXISTS (SELECT 1 FROM public.students WHERE id = p_student AND center_id = v_center) THEN
    RAISE EXCEPTION 'not_allowed';
  END IF;
  RETURN COALESCE((SELECT jsonb_agg(jsonb_build_object(
    'id', id, 'center_id', center_id, 'student_id', student_id, 'device_id', device_id,
    'blocked', blocked, 'note', note, 'first_seen', first_seen, 'last_seen', last_seen, 'blocked_at', blocked_at
  ) ORDER BY last_seen DESC) FROM public.student_device_sessions
  WHERE center_id = v_center AND student_id = p_student), '[]'::JSONB);
END;
$$;
GRANT EXECUTE ON FUNCTION public.list_student_devices(TEXT) TO authenticated;

-- حجب جهاز واحد أو إلغاء حجبه. عند الحجب تنتهي جلسة هذا الجهاز فقط فور الفحص التالي.
CREATE OR REPLACE FUNCTION public.set_student_device_blocked(
  p_student TEXT, p_device TEXT, p_blocked BOOLEAN, p_note TEXT DEFAULT ''
)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_center UUID := public.my_center_id(); v_updated INT;
BEGIN
  IF v_center IS NULL OR NOT public.admin_owns_center(v_center)
     OR NOT EXISTS (SELECT 1 FROM public.students WHERE id = p_student AND center_id = v_center) THEN
    RAISE EXCEPTION 'not_allowed';
  END IF;
  IF p_device IS NULL OR length(trim(p_device)) < 8 THEN RAISE EXCEPTION 'invalid_device'; END IF;
  UPDATE public.student_device_sessions
  SET blocked = COALESCE(p_blocked, false), note = COALESCE(trim(p_note), ''),
      blocked_at = CASE WHEN p_blocked THEN now() ELSE NULL END
  WHERE center_id = v_center AND student_id = p_student AND device_id = trim(p_device);
  GET DIAGNOSTICS v_updated = ROW_COUNT;
  IF v_updated = 0 THEN RAISE EXCEPTION 'student_device_not_found'; END IF;
  IF p_blocked THEN
    DELETE FROM public.user_active_sessions uas
    USING public.profiles p
    WHERE p.id = uas.user_id AND p.student_id = p_student AND p.center_id = v_center
      AND uas.device_id = trim(p_device);
  END IF;
END;
$$;
GRANT EXECUTE ON FUNCTION public.set_student_device_blocked(TEXT, TEXT, BOOLEAN, TEXT) TO authenticated;

-- إغلاق قناة الجلسة الحالية للطالب دون حجبه دائماً؛ يمكنه تسجيل الدخول لاحقاً.
CREATE OR REPLACE FUNCTION public.disconnect_student_session(p_student TEXT)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_center UUID := public.my_center_id();
BEGIN
  IF v_center IS NULL OR NOT public.admin_owns_center(v_center)
     OR NOT EXISTS (SELECT 1 FROM public.students WHERE id = p_student AND center_id = v_center) THEN
    RAISE EXCEPTION 'not_allowed';
  END IF;
  DELETE FROM public.user_active_sessions uas
  USING public.profiles p
  WHERE p.id = uas.user_id AND p.student_id = p_student AND p.center_id = v_center;
END;
$$;
GRANT EXECUTE ON FUNCTION public.disconnect_student_session(TEXT) TO authenticated;

-- يمنع إعادة الدخول من الجهاز المحجوب، مع الإبقاء على حماية محاولات الدخول الأصلية.
CREATE OR REPLACE FUNCTION public.check_login_allowed(p_email TEXT, p_device TEXT)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_failures INT;
BEGIN
  DELETE FROM public.login_attempts WHERE created_at < now() - interval '24 hours';
  SELECT count(*) INTO v_failures FROM public.login_attempts
   WHERE email = lower(trim(p_email)) AND success = false AND created_at > now() - interval '15 minutes';
  IF v_failures >= 10 THEN RAISE EXCEPTION 'login_rate_limited'; END IF;
  IF p_device IS NOT NULL AND p_device <> '' THEN
    SELECT count(*) INTO v_failures FROM public.login_attempts
     WHERE device_id = p_device AND success = false AND created_at > now() - interval '15 minutes';
    IF v_failures >= 30 THEN RAISE EXCEPTION 'login_rate_limited'; END IF;
    IF EXISTS (
      SELECT 1 FROM public.profiles p
      JOIN public.student_device_sessions d ON d.center_id = p.center_id AND d.student_id = p.student_id
      WHERE p.role = 'student' AND lower(COALESCE(p.email, '')) = lower(trim(p_email))
        AND d.device_id = trim(p_device) AND d.blocked
    ) THEN RAISE EXCEPTION 'student_device_blocked'; END IF;
  END IF;
END;
$$;
GRANT EXECUTE ON FUNCTION public.check_login_allowed(TEXT, TEXT) TO anon, authenticated;

-- ----------------------------------------------------------------------------
-- ٢) تسوية عجز عهدة: إما مصروف يتحمله السنتر أو خصم على صاحب العهدة.
-- السلفة والخصم يظلان منفصلين محاسبياً، ولا يتكون قيد مكرر.
-- ----------------------------------------------------------------------------
ALTER TABLE public.staff_custody
  ADD COLUMN IF NOT EXISTS shortage_resolved_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS shortage_resolution TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS shortage_resolution_note TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS shortage_resolved_at TIMESTAMPTZ;

-- إعادة الدالة مع حقول التسوية كي تظهر حالة العجز في واجهة العهدة.
CREATE OR REPLACE FUNCTION public.get_custody_overview(p_from DATE DEFAULT NULL, p_to DATE DEFAULT NULL)
RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
DECLARE v_center UUID := public.my_center_id(); v_role TEXT := public.my_role();
BEGIN
  IF v_center IS NULL THEN RETURN '[]'::JSONB; END IF;
  IF NOT public.admin_owns_center(v_center) AND v_role NOT IN ('manager','secretary') THEN RAISE EXCEPTION 'not_allowed'; END IF;
  -- يظل الموظف قادراً على تسليم عهدته التشغيلية، أما كشف المالك المالي
  -- فلا يُقرأ خارج فترة تفعيل المحاسبة حتى لا يتجاوز بوابة الخدمة عبر RPC.
  IF public.admin_owns_center(v_center) AND NOT public.center_accounting_enabled(v_center) THEN
    RAISE EXCEPTION 'accounting_not_enabled';
  END IF;
  RETURN COALESCE((
    WITH collected AS (
      SELECT l.created_by AS staff_id, COALESCE(NULLIF(l.created_by_name, ''), p.full_name, 'موظف') AS staff_name,
        l.occurred_on AS custody_date, SUM(l.amount)::numeric AS expected_amount
      FROM public.center_ledger l LEFT JOIN public.profiles p ON p.id = l.created_by
      WHERE l.center_id = v_center AND l.entry_type = 'payment_collection'
        AND (p_from IS NULL OR l.occurred_on >= p_from) AND (p_to IS NULL OR l.occurred_on <= p_to)
        AND (public.admin_owns_center(v_center) OR l.created_by = auth.uid())
      GROUP BY l.created_by, COALESCE(NULLIF(l.created_by_name, ''), p.full_name, 'موظف'), l.occurred_on
    ), combined AS (
      SELECT c.staff_id, c.staff_name, c.custody_date, c.expected_amount, sc.id, COALESCE(sc.delivered_amount, 0) AS delivered_amount,
        COALESCE(sc.status, 'open') AS status, COALESCE(sc.notes, '') AS notes, sc.submitted_at, sc.created_at,
        COALESCE(sc.shortage_resolved_amount, 0) AS shortage_resolved_amount, COALESCE(sc.shortage_resolution, '') AS shortage_resolution,
        COALESCE(sc.shortage_resolution_note, '') AS shortage_resolution_note, sc.shortage_resolved_at
      FROM collected c LEFT JOIN public.staff_custody sc ON sc.center_id = v_center AND sc.staff_id = c.staff_id AND sc.custody_date = c.custody_date
      UNION ALL
      SELECT sc.staff_id, COALESCE(p.full_name, 'موظف'), sc.custody_date, sc.expected_amount, sc.id, sc.delivered_amount, sc.status, sc.notes, sc.submitted_at, sc.created_at,
        COALESCE(sc.shortage_resolved_amount, 0), COALESCE(sc.shortage_resolution, ''), COALESCE(sc.shortage_resolution_note, ''), sc.shortage_resolved_at
      FROM public.staff_custody sc LEFT JOIN public.profiles p ON p.id = sc.staff_id
      WHERE sc.center_id = v_center AND (p_from IS NULL OR sc.custody_date >= p_from) AND (p_to IS NULL OR sc.custody_date <= p_to)
        AND (public.admin_owns_center(v_center) OR sc.staff_id = auth.uid())
        AND NOT EXISTS (SELECT 1 FROM collected c WHERE c.staff_id = sc.staff_id AND c.custody_date = sc.custody_date)
    )
    SELECT jsonb_agg(jsonb_build_object('id',id,'staff_id',staff_id,'staff_name',staff_name,'custody_date',custody_date,
      'expected_amount',expected_amount,'delivered_amount',delivered_amount,'status',status,'notes',notes,'submitted_at',submitted_at,'created_at',created_at,
      'shortage_resolved_amount',shortage_resolved_amount,'shortage_resolution',shortage_resolution,'shortage_resolution_note',shortage_resolution_note,'shortage_resolved_at',shortage_resolved_at)
      ORDER BY custody_date DESC, staff_name)
    FROM combined
  ), '[]'::JSONB);
END;
$$;
GRANT EXECUTE ON FUNCTION public.get_custody_overview(DATE, DATE) TO authenticated;

-- لا يسمح بتعديل تسليم العهدة ليصبح أقل من عجز سُوي فعلاً.
CREATE OR REPLACE FUNCTION public.settle_staff_custody(
  p_center UUID, p_staff UUID, p_date DATE, p_delivered NUMERIC, p_notes TEXT DEFAULT ''
)
RETURNS UUID LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_expected NUMERIC := 0; v_status TEXT; v_id UUID; v_resolved NUMERIC := 0;
BEGIN
  PERFORM public.assert_accounting_owner(p_center);
  PERFORM public.assert_accounting_employee(p_center, p_staff);
  IF COALESCE(p_delivered, -1) < 0 THEN RAISE EXCEPTION 'invalid_custody_amount'; END IF;
  SELECT COALESCE(SUM(amount), 0) INTO v_expected FROM public.center_ledger
   WHERE center_id = p_center AND created_by = p_staff AND entry_type = 'payment_collection' AND occurred_on = COALESCE(p_date, CURRENT_DATE);
  SELECT COALESCE(shortage_resolved_amount, 0) INTO v_resolved FROM public.staff_custody
   WHERE center_id = p_center AND staff_id = p_staff AND custody_date = COALESCE(p_date, CURRENT_DATE) FOR UPDATE;
  IF v_resolved > GREATEST(v_expected - p_delivered, 0) THEN RAISE EXCEPTION 'custody_resolution_exceeds_shortage'; END IF;
  v_status := CASE WHEN p_delivered = v_expected THEN 'matched' WHEN p_delivered < v_expected THEN 'shortage' ELSE 'surplus' END;
  INSERT INTO public.staff_custody(center_id, staff_id, custody_date, expected_amount, delivered_amount, status, notes, submitted_at, submitted_by)
  VALUES(p_center, p_staff, COALESCE(p_date,CURRENT_DATE), v_expected, p_delivered, v_status, COALESCE(trim(p_notes),''), now(), auth.uid())
  ON CONFLICT(center_id,staff_id,custody_date) DO UPDATE
    SET expected_amount=EXCLUDED.expected_amount, delivered_amount=EXCLUDED.delivered_amount, status=EXCLUDED.status,
        notes=EXCLUDED.notes, submitted_at=now(), submitted_by=auth.uid()
  RETURNING id INTO v_id;
  RETURN v_id;
END;
$$;
GRANT EXECUTE ON FUNCTION public.settle_staff_custody(UUID, UUID, DATE, NUMERIC, TEXT) TO authenticated;

CREATE OR REPLACE FUNCTION public.resolve_staff_custody_shortage(
  p_custody UUID, p_method TEXT, p_amount NUMERIC, p_note TEXT DEFAULT ''
)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_custody public.staff_custody%ROWTYPE; v_shortage NUMERIC; v_available NUMERIC;
  v_amount NUMERIC := COALESCE(p_amount, 0); v_actor_name TEXT; v_ledger UUID; v_deduction UUID;
BEGIN
  SELECT * INTO v_custody FROM public.staff_custody WHERE id = p_custody FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'custody_not_found'; END IF;
  PERFORM public.assert_accounting_owner(v_custody.center_id);
  v_shortage := GREATEST(v_custody.expected_amount - v_custody.delivered_amount, 0);
  v_available := GREATEST(v_shortage - COALESCE(v_custody.shortage_resolved_amount, 0), 0);
  IF v_shortage <= 0 THEN RAISE EXCEPTION 'custody_has_no_shortage'; END IF;
  IF p_method NOT IN ('expense','deduction') THEN RAISE EXCEPTION 'invalid_custody_resolution'; END IF;
  IF v_amount <= 0 OR v_amount > v_available THEN RAISE EXCEPTION 'invalid_custody_resolution_amount'; END IF;
  SELECT full_name INTO v_actor_name FROM public.profiles WHERE id = auth.uid();

  IF p_method = 'expense' THEN
    INSERT INTO public.center_ledger(center_id, kind, entry_type, category, description, amount, occurred_on, created_by, created_by_name, period_month, period_year, affects_profit)
    VALUES(v_custody.center_id, 'expense', 'general', 'تسوية عجز عهدة',
      'عجز عهدة ' || COALESCE(v_custody.custody_date::text, '') || ' — ' || COALESCE(v_custody.notes, '') || CASE WHEN trim(p_note) <> '' THEN ' — ' || trim(p_note) ELSE '' END,
      v_amount, CURRENT_DATE, auth.uid(), COALESCE(v_actor_name, ''), EXTRACT(MONTH FROM CURRENT_DATE)::INT, EXTRACT(YEAR FROM CURRENT_DATE)::INT, true)
    RETURNING id INTO v_ledger;
  ELSE
    INSERT INTO public.staff_deductions(center_id, staff_id, amount, reason, notes, occurred_on, created_by)
    VALUES(v_custody.center_id, v_custody.staff_id, v_amount, 'تسوية عجز عهدة',
      'عجز عهدة بتاريخ ' || v_custody.custody_date::text || CASE WHEN trim(p_note) <> '' THEN ' — ' || trim(p_note) ELSE '' END,
      CURRENT_DATE, auth.uid()) RETURNING id INTO v_deduction;
  END IF;

  UPDATE public.staff_custody SET shortage_resolved_amount = shortage_resolved_amount + v_amount,
    shortage_resolution = CASE WHEN shortage_resolved_amount + v_amount >= v_shortage
      THEN CASE WHEN shortage_resolution <> '' AND shortage_resolution <> p_method THEN 'mixed' ELSE p_method END
      ELSE CASE WHEN shortage_resolution <> '' AND shortage_resolution <> p_method THEN 'mixed' ELSE p_method END END,
    shortage_resolution_note = CASE WHEN trim(p_note) = '' THEN shortage_resolution_note ELSE trim(p_note) END,
    shortage_resolved_at = now()
  WHERE id = v_custody.id;
  RETURN jsonb_build_object('ledger_id', v_ledger, 'deduction_id', v_deduction, 'remaining', v_available - v_amount);
END;
$$;
GRANT EXECUTE ON FUNCTION public.resolve_staff_custody_shortage(UUID, TEXT, NUMERIC, TEXT) TO authenticated;


-- ----------------------------------------------------------------------------
-- ٣) تصحيح القيود التي أُدخلت يدوياً. تحصيل الطالب لا يعدل من الدفتر حتى
-- لا ينفصل عن إيصال الطالب؛ يُعدّل من شاشة التحصيل ومصدره الأصلية.
-- صرف الراتب لا يحرر مبلغ النقد مباشرة لأن به تسوية سلف وخصومات مترابطة؛
-- يمكن تعديل تاريخه وبيانه، وتتم أي قيمة جديدة بصرف جديد/عكس موثق لاحقاً.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.amend_accounting_ledger_entry(
  p_entry UUID, p_date DATE, p_category TEXT, p_description TEXT, p_amount NUMERIC DEFAULT NULL
)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_row public.center_ledger%ROWTYPE; v_applied NUMERIC := 0; v_other_advances NUMERIC := 0;
BEGIN
  SELECT * INTO v_row FROM public.center_ledger WHERE id = p_entry FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'ledger_entry_not_found'; END IF;
  PERFORM public.assert_accounting_owner(v_row.center_id);
  IF v_row.entry_type = 'payment_collection' OR v_row.source_payment_id IS NOT NULL THEN
    RAISE EXCEPTION 'ledger_source_managed';
  END IF;
  IF COALESCE(trim(p_description), '') IS NULL THEN RAISE EXCEPTION 'invalid_ledger_entry'; END IF;
  IF p_date IS NULL THEN RAISE EXCEPTION 'invalid_ledger_entry'; END IF;
  IF v_row.entry_type = 'salary' AND p_amount IS NOT NULL AND p_amount <> v_row.amount THEN
    RAISE EXCEPTION 'salary_amount_requires_reversal';
  END IF;
  IF v_row.entry_type = 'advance' AND p_amount IS NOT NULL THEN
    IF p_amount <= 0 THEN RAISE EXCEPTION 'invalid_advance_amount'; END IF;
    SELECT COALESCE(SUM(advance_applied), 0) INTO v_applied FROM public.center_ledger
      WHERE center_id = v_row.center_id AND employee_id = v_row.employee_id AND entry_type = 'salary';
    SELECT COALESCE(SUM(amount), 0) INTO v_other_advances FROM public.center_ledger
      WHERE center_id = v_row.center_id AND employee_id = v_row.employee_id AND entry_type = 'advance' AND id <> v_row.id;
    IF p_amount + v_other_advances < v_applied THEN RAISE EXCEPTION 'advance_edit_below_applied'; END IF;
  ELSIF p_amount IS NOT NULL AND p_amount <= 0 THEN
    RAISE EXCEPTION 'invalid_ledger_entry';
  END IF;
  UPDATE public.center_ledger SET
    occurred_on = p_date,
    period_month = EXTRACT(MONTH FROM p_date)::INT,
    period_year = EXTRACT(YEAR FROM p_date)::INT,
    category = CASE WHEN v_row.entry_type IN ('salary','advance','commission') THEN category ELSE COALESCE(NULLIF(trim(p_category), ''), category) END,
    description = COALESCE(trim(p_description), ''),
    amount = CASE WHEN p_amount IS NULL OR v_row.entry_type = 'salary' THEN amount ELSE p_amount END
  WHERE id = v_row.id;
END;
$$;
GRANT EXECUTE ON FUNCTION public.amend_accounting_ledger_entry(UUID, DATE, TEXT, TEXT, NUMERIC) TO authenticated;

CREATE OR REPLACE FUNCTION public.amend_staff_deduction(
  p_deduction UUID, p_amount NUMERIC, p_reason TEXT, p_notes TEXT, p_date DATE
)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_row public.staff_deductions%ROWTYPE;
BEGIN
  SELECT * INTO v_row FROM public.staff_deductions WHERE id = p_deduction FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'deduction_not_found'; END IF;
  PERFORM public.assert_accounting_owner(v_row.center_id);
  IF p_amount IS NULL OR p_amount <= 0 OR p_amount < v_row.applied_amount OR COALESCE(trim(p_reason), '') = '' OR p_date IS NULL THEN
    RAISE EXCEPTION 'invalid_staff_deduction_edit';
  END IF;
  UPDATE public.staff_deductions SET amount = p_amount, reason = trim(p_reason), notes = COALESCE(trim(p_notes), ''), occurred_on = p_date,
    status = CASE WHEN v_row.applied_amount >= p_amount THEN 'settled' WHEN v_row.applied_amount > 0 THEN 'partial' ELSE 'open' END,
    updated_at = now()
  WHERE id = v_row.id;
END;
$$;
GRANT EXECUTE ON FUNCTION public.amend_staff_deduction(UUID, NUMERIC, TEXT, TEXT, DATE) TO authenticated;

COMMIT;
